# fly.toml app configuration file generated for tic-tac-spin-drop on 2023-09-28T23:18:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tic-tac-spin-drop"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
